services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: up_training_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    networks:
      - up_training_network
    depends_on:
      - db

  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    container_name: up_training_nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html
    networks:
      - up_training_network
    depends_on:
      - app
      - php

  php:
    image: php:8.2-fpm
    container_name: up_training_php
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:8.0
    container_name: up_training_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - up_training_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - up_training_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: up_training_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 512M
    networks:
      - up_training_network
    depends_on:
      - db

networks:
  up_training_network:

volumes:
  up_training_data:
