services:
  up_training:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: benjmasub/up_training:latest
    container_name: up_training_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=production
